import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//
export const inter = Inter({
  subsets: ["latin"],
});

const aban = localFont({
  src: [
    {
      path: "../assets/fonts/Aban.ttf",
      weight: "500",
    },
    {
      path: "../assets/fonts/Aban-bold.ttf",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={inter.className}
        className={aban.className}
      >
        {children}
      </body>
    </html>
  );
}
